# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8e39950885e801e7be5217c5d25745055daaf33c289bebd82a97a35d42c861668d91d37b04ec24107084dcd891fcd216f6e244bc55afb659c2fe5d77add4ac9

test:
  secret_key_base: 90955bb8321b1974cd12a256060814c3a0ec2f6f8f69cc5d38b0b02160c5c69e5c2069b8a208663023030cd22d07898934591df54c4a309adca77200773b7015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
